# Generated by Django 2.2.4 on 2020-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
