# Generated by Django 2.2.4 on 2020-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200422_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='app_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='app_user',
            new_name='user',
        ),
    ]
